<a href="https://colab.research.google.com/github/hfelizzola/Investigaciones-de-Operaciones-I/blob/main/flujo-redes/07_ruta_mas_corta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Ruta Más Corta

In [1]:
!pip install gamspy --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 251.2/251.2 kB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 27.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.6/31.6 MB 38.7 MB/s eta 0:00:00

In [2]:
import numpy as np
import pandas as pd
from gamspy import Container, Set, Parameter, Variable, Sum, Sense, Model, Equation, Options, Alias

In [3]:
[i+1 for i in range(5)]

[1, 2, 3, 4, 5]

In [5]:
# Modelo Matemático

# Container
m = Container()

# Set
i = Set(m , name='i', records=[i+1 for i in range(5)])
j = Alias(m, name="j", alias_with=i)

# Variable
x = Variable(m, name="x", domain=[i,j], type="positive")

# Función objetivo
objetivo = 100*x[1,2] + 30*x[1,3] + 20*x[2,3] + 10*x[3,4] + 15*x[4,2] + 60*x[3,5] + 50*x[4,5]

# Equation
nodo1 = Equation(m , name="nodo1")
nodo1[...] = 1 - x[1,2] - x[1,3] == 0

nodo2 = Equation(m , name="nodo2")
nodo2[...] = x[1,2] + x[4,2] - x[2,3] == 0

nodo3 = Equation(m , name="nodo3")
nodo3[...] = x[1,3] + x[2,3] - x[3,4] - x[3,5] == 0

nodo4 = Equation(m , name="nodo4")
nodo4[...] = x[3,4] - x[4,2] - x[4,5] == 0

nodo5 = Equation(m , name="nodo5")
nodo5[...] = x[3,5] + x[4,5] - 1 == 0

modelo = Model(m, objective=objetivo,
               problem="LP", equations=[nodo1, nodo2, nodo3, nodo4, nodo5],
               sense=Sense.MIN, name="modelo")
modelo.solve()

,Solver Status,Model Status,Objective,Num of Equations,Num of Variables,Model Type,Solver,Solver Time
0,NormalCompletion,OptimalGlobal,90.0,6.0,8.0,LP,CPLEX,0.023

In [9]:
x.records.pivot_table(index='i', columns='j', values='level', fill_value=0)

/tmp/ipykernel_12292/3656916998.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  x.records.pivot_table(index='i', columns='j', values='level', fill_value=0)

j    2    3    4    5
i
1  0.0  1.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  1.0
4  0.0  0.0  0.0  0.0